# Generated by Django 6.1.1 on 2026-09-18 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='coefficient',
        ),
        migrations.AddField(
            model_name='matiere',
            name='credits',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de crédits LMD/ECTS'),
        ),
        migrations.AddField(
            model_name='note',
            name='session',
            field=models.CharField(choices=[('normale', 'Session normale'), ('rattrapage', 'Rattrapage')], default='normale', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='periode',
            field=models.CharField(default='Semestre 1', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'session', 'periode')},
        ),
    ]
